[opener]
edit = [
  {
    run = 'zellij run -- hx "$0"',
    desc = "Helix (new pane)",
    block = true,
    for = "unix"
  },
]

[mgr]
show_hidden = true
show_symlink = true
sort_translit = true
linemode = "size_and_mtime"

[preview]
wrap = "yes"