theme = "github_light_high_contrast"

[editor]
mouse = true
insert-final-newline = false
bufferline = "multiple"
default-line-ending = "lf"
popup-border = "all"
rulers = [80, 120]
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = true
goto-reference-include-declaration = true
display-signature-help-docs = true
auto-signature-help = false

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "all"
nnbsp = "none"
newline = "none"

[editor.indent-guides]
render = true

[editor.statusline]
right = [
  "diagnostics",
  "selections",
  "register",
  "position",
  "file-type",
  "file-line-ending",
  "file-indent-style",
  "file-encoding",
  "version-control",
]

[editor.auto-save]
focus-lost = true

[editor.auto-save.after-delay]
enable = true
timeout = 2000

[keys.insert]
"esc" = ["normal_mode", ":w"]
