[[language]]
name = "python"
language-servers = ["pylsp", "ruff"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }
scope = "source.python"
rulers = [88]

[[language]]
name = "go"
auto-format = true
formatter = { command = "golangci-lint", args = ["fmt", "--stdin"] }
language-servers = ["gopls", "golangci-lint-lsp"]
rulers = [88]

[[language]]
name = "markdown"
language-servers = ["marksman"]
soft-wrap = { enable = true, max-wrap = 25, wrap-indicator = "" }
auto-format = true
formatter = { command = "dprint-debug", args = ["fmt", "--stdin", "md", "--config-discovery=global"] }
rulers = [80]

[[language]]
auto-format = false
name = "bash"
file-types = ["sh", "bash", "env", ".bashrc", ".bash_profile", ".profile"]
rulers = [80]

[[language]]
auto-format = false
name = "sql"
language-servers = ["postgres-lsp"]

[[language]]
auto-format = false
name = "json"
rulers = [120]

[[language]]
auto-format = false
name = "jsonc"
rulers = [120]

[[language]]
auto-format = false
name = "dockerfile"
rulers = [120]

[[language]]
auto-format = false
name = "git-commit"
rulers = [50, 72]

[[language]]
auto-format = false
name = "git-rebase"
rulers = [50, 72]

# language servers

[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log", "serve"]

[language-server.ruff]
command = "ruff"
args = ["lsp"]

[language-server.pylsp]
command = "pylsp"

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.json.path", "stdout", "--show-stats=false", "--issues-exit-code=1"]

[language-server.marksman]
command = "marksman"

[language.debugger]
name = "debugpy"
transport = "stdio"
command = "python3"
args = ["-m", "debugpy.adapter"]

[language-server.postgres-lsp]
command = "postgres-language-server"
args = ["--stdio"]

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]
args = { mode = "debug", program = "{0}" }
